/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_AddCameraMessage_H_
#define	_AddCameraMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AddCameraMessage */
typedef struct AddCameraMessage {
	long	 cameraid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AddCameraMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddCameraMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _AddCameraMessage_H_ */
#include <asn_internal.h>
